### ISSUE TITLE
No module named discord

### ISSUE THREAD

**Issue by jtagcat** [belguawhale/DiscordSelfBot#3]
root@prone:~/DiscordSelfBot# python3 selfbot.py 
Traceback (most recent call last):
  File "selfbot.py", line 1, in <module>
    import discord
ImportError: No module named 'discord'

**Comment by JoshuaSmeda** [comment]
Install discord module:

https://pypi.org/project/discord.py/

**Comment by jtagcat** [comment]
Sorry to bother, now moved on from discord to riot.im / matrix.org
